### ISSUE TITLE
enzyme build fail with clang on for windows

### ISSUE THREAD

**Issue by superustc** [JuliaPackaging/Yggdrasil#11548]
I try to use Enzyme/build_tarballs.jl to build enzyme for windows x86_64 with llvm_assertion off, cxx11, and llvm 16
 
https://github.com/JuliaPackaging/Yggdrasil/blob/master/E/Enzyme/build_tarballs.jl

with 
```

llvm_assertions in (false)

...

    # ─── keep ONLY Windows ─────────────────────────────────────────────
    filter!(p -> os(p) == "windows", platforms)
    filter!(p -> arch(p) == "x86_64", platforms)
    filter!(p -> cxxstring_abi(p) == "cxx11", platforms)
    # ───────────────────────────────────────────────────────────────────

```
When -DENZYME_CLANG off, it works fine. Whent it is on, it gives the following errors  with llvm_versions = [v"16.0.6"]
```

	 julia build_tarballs.jl --debug
	[ Info: Building for x86_64-w64-mingw32-cxx11-llvm_version+16
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:394
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:473
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced 4 more times
	
	ld.lld: error: undefined symbol: clang::Sema::Diag(clang::SourceLocation, unsigned int, bool)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:246
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::diagAppertainsToDecl(clang::Sema&, clang::ParsedAttr const&, clang::Decl const*) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:0
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:380
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::diagAppertainsToDecl(clang::Sema&, clang::ParsedAttr const&, clang::Decl const*) const)
	>>> referenced 10 more times
	
	ld.lld: error: undefined symbol: clang::Sema::SemaDiagnosticBuilder::~SemaDiagnosticBuilder()
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:246
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::diagAppertainsToDecl(clang::Sema&, clang::ParsedAttr const&, clang::Decl const*) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:0
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:380
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::diagAppertainsToDecl(clang::Sema&, clang::ParsedAttr const&, clang::Decl const*) const)
	>>> referenced 10 more times
	
	ld.lld: error: undefined symbol: clang::Expr::IgnoreParenCasts()
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:263
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	
	ld.lld: error: undefined symbol: clang::AnnotateAttr::Create(clang::ASTContext&, llvm::StringRef, clang::Expr**, unsigned int, clang::AttributeCommonInfo const&)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:272
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:394
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	
	ld.lld: error: undefined symbol: clang::DiagnosticIDs::getCustomDiagID(clang::DiagnosticIDs::Level, llvm::StringRef)
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/Basic/Diagnostic.h:869
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/Basic/Diagnostic.h:869
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/Basic/Diagnostic.h:869
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced 6 more times
	
	ld.lld: error: undefined symbol: clang::DeclContext::getRedeclContext()
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/AST/DeclBase.h:2089
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:(clang::VarDecl::hasLocalStorage() const)
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/AST/DeclBase.h:2089
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:(clang::VarDecl::hasLocalStorage() const)
	
	ld.lld: error: undefined symbol: clang::Decl::castFromDeclContext(clang::DeclContext const*)
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/AST/DeclBase.h:2623
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/AST/DeclBase.h:2623
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/AST/DeclBase.h:2623
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced 3 more times
	
	ld.lld: error: undefined symbol: clang::RecordDecl::Create(clang::ASTContext const&, clang::TagTypeKind, clang::DeclContext*, clang::SourceLocation, clang::SourceLocation, clang::IdentifierInfo*, clang::RecordDecl*)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:458
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:563
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:663
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeSparseAccumulateAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	
	ld.lld: error: undefined symbol: clang::CXXRecordDecl::Create(clang::ASTContext const&, clang::TagTypeKind, clang::DeclContext*, clang::SourceLocation, clang::SourceLocation, clang::IdentifierInfo*, clang::CXXRecordDecl*, bool)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:455
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:560
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:660
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeSparseAccumulateAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	
	ld.lld: error: undefined symbol: clang::TagDecl::startDefinition()
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:462
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:567
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:667
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeSparseAccumulateAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	
	ld.lld: error: undefined symbol: clang::DeclarationName::getAsString[abi:cxx11]() const
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/AST/Decl.h:290
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/AST/Decl.h:290
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+16/destdir/include/clang/AST/Decl.h:290
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeSparseAccumulateAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	
	ld.lld: error: undefined symbol: clang::ASTContext::getPointerType(clang::QualType) const
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:467
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:572
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:670
	>>>               Enzyme/CMakeFiles/ClangEnzyme-16.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeSparseAccumulateAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
	
	ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
	clang++: error: linker command failed with exit code 1 (use -v to see invocation)
	ninja: subcommand failed
	Previous command exited with 1
	┌ Warning: Build failed, the following log files were generated:
	│   - ${WORKSPACE}/srcdir/Enzyme/build/CMakeFiles/CMakeError.log
	│   - ${WORKSPACE}/srcdir/Enzyme/build/CMakeFiles/CMakeOutput.log
	│   - ${WORKSPACE}/srcdir/Enzyme/build-native/BCLoad/gsl/CMakeFiles/CMakeError.log
	│   - ${WORKSPACE}/srcdir/Enzyme/build-native/BCLoad/gsl/CMakeFiles/CMakeOutput.log
	│   - ${WORKSPACE}/srcdir/Enzyme/build-native/CMakeFiles/CMakeError.log
	│   - ${WORKSPACE}/srcdir/Enzyme/build-native/CMakeFiles/CMakeOutput.log
	│ 
	│ Launching debug shell:
	└ @ BinaryBuilder ~/.julia/packages/BinaryBuilder/ALifR/src/AutoBuild.jl:913
```

Additionally, if using LLVM 18  (llvm_versions = [v"18.1.7"]) and enabling the Windows build, it gives 

```
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp:3905:42: warning: ‘val’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3905 |           Value *tofree = gutils->lookupM(val, Builder2, ValueToValueMapTy(),
      |                           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3906 |                                           /*tryLegalRecompute*/ false);
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[108/112] Linking CXX shared module Enzyme/LLVMEnzyme-18.dll
ninja: job failed: : && /opt/bin/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+18/x86_64-w64-mingw32-g++ --sysroot=/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/ -Wall -fno-rtti  -Werror=unused-variable -Werror=dangling-else -Werror=unused-but-set-variable -Werror=return-type -Werror=nonnull -Werror=unused-result -Werror=reorder -Werror=switch -O2 -g -ggdb  -Wl,--gc-sections -shared -o Enzyme/LLVMEnzyme-18.dll -Wl,--major-image-version,0,--minor-image-version,0 Enzyme/CMakeFiles/LLVMEnzyme-18.dir/ActivityAnalysis.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/ActivityAnalysisPrinter.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/CApi.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/CacheUtility.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/CallDerivatives.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/DiffeGradientUtils.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/DifferentialUseAnalysis.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/Enzyme.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/EnzymeLogic.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/FunctionUtils.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/GradientUtils.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/InstructionBatcher.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/JLInstSimplify.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/MustExitScalarEvolution.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/PreserveNVVM.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/TraceGenerator.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/TraceInterface.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/TraceUtils.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/Utils.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/TypeAnalysis/TypeTree.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/TypeAnalysis/TypeAnalysis.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/TypeAnalysis/TypeAnalysisPrinter.cpp.obj Enzyme/CMakeFiles/LLVMEnzyme-18.dir/TypeAnalysis/RustDebugInfo.cpp.obj  /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+18/destdir/lib/libLLVM-18jl.dll.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && :
/opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld: Enzyme/CMakeFiles/LLVMEnzyme-18.dir/FunctionUtils.cpp.obj: in function `llvm::detail::AnalysisResultModel<llvm::Loop, llvm::OuterAnalysisManagerProxy<llvm::AnalysisManager<llvm::Function>, llvm::Loop, llvm::LoopStandardAnalysisResults&>, llvm::OuterAnalysisManagerProxy<llvm::AnalysisManager<llvm::Function>, llvm::Loop, llvm::LoopStandardAnalysisResults&>::Result, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>::Invalidator, true>::invalidate(llvm::Loop&, llvm::PreservedAnalyses const&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>::Invalidator&)':
/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/usr/local/include/llvm/IR/PassManagerInternal.h:260: undefined reference to `llvm::OuterAnalysisManagerProxy<llvm::AnalysisManager<llvm::Function>, llvm::Loop, llvm::LoopStandardAnalysisResults&>::Result::invalidate(llvm::Loop&, llvm::PreservedAnalyses const&, llvm::AnalysisManager<llvm::Loop, llvm::LoopStandardAnalysisResults&>::Invalidator&)'
collect2: error: ld returned 1 exit status
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp: In member function ‘bool AdjointGenerator::handleKnownCallDerivatives(llvm::CallInst&, llvm::Function*, llvm::StringRef, bool, const std::vector<bool>&, llvm::CallInst*)’:
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp:2754:29: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 2754 |           for (int i = 0; i < gutils->getWidth(); i++) {
      |                           ~~^~~~~~~~~~~~~~~~~~~~
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp:3905:42: warning: ‘val’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3905 |           Value *tofree = gutils->lookupM(val, Builder2, ValueToValueMapTy(),
      |                           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3906 |                                           /*tryLegalRecompute*/ false);
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp: In member function ‘bool AdjointGenerator::handleKnownCallDerivatives(llvm::CallInst&, llvm::Function*, llvm::StringRef, bool, const std::vector<bool>&, llvm::CallInst*)’:
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp:2754:29: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 2754 |           for (int i = 0; i < gutils->getWidth(); i++) {
      |                           ~~^~~~~~~~~~~~~~~~~~~~
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp:3905:42: warning: ‘val’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3905 |           Value *tofree = gutils->lookupM(val, Builder2, ValueToValueMapTy(),
      |                           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3906 |                                           /*tryLegalRecompute*/ false);
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp: In member function ‘bool AdjointGenerator::handleKnownCallDerivatives(llvm::CallInst&, llvm::Function*, llvm::StringRef, bool, const std::vector<bool>&, llvm::CallInst*)’:
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp:2754:29: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 2754 |           for (int i = 0; i < gutils->getWidth(); i++) {
      |                           ~~^~~~~~~~~~~~~~~~~~~~
/workspace/srcdir/Enzyme/enzyme/Enzyme/CallDerivatives.cpp:3905:42: warning: ‘val’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 3905 |           Value *tofree = gutils->lookupM(val, Builder2, ValueToValueMapTy(),
      |                           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3906 |                                           /*tryLegalRecompute*/ false);
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: subcommand failed
Previous command exited with 1
┌ Warning: Build failed, the following log files were generated:
│   - ${WORKSPACE}/srcdir/Enzyme/build/CMakeFiles/CMakeError.log
│   - ${WORKSPACE}/srcdir/Enzyme/build/CMakeFiles/CMakeOutput.log
│   - ${WORKSPACE}/srcdir/Enzyme/build-native/BCLoad/gsl/CMakeFiles/CMakeError.log
│   - ${WORKSPACE}/srcdir/Enzyme/build-native/BCLoad/gsl/CMakeFiles/CMakeOutput.log
│   - ${WORKSPACE}/srcdir/Enzyme/build-native/CMakeFiles/CMakeError.log
│   - ${WORKSPACE}/srcdir/Enzyme/build-native/CMakeFiles/CMakeOutput.log
│ 
│ Launching debug shell:
└ @ BinaryBuilder ~/.julia/packages/BinaryBuilder/ALifR/src/AutoBuild.jl:913
```

**Comment by giordano** [comment]
CC @wsmoses @vchuravy.

**Comment by giordano** [comment]
Maybe you can elaborate what you're trying to achieve?

**Comment by superustc** [comment]
@giordano @wsmoses @vchuravy  I am trying to use this jl to build enzyme as clang add-in for Windows. Currently, there is no reliable way to build enzyme for Windows yet. @wsmoses knows the background. I shared the need and challenges of Windows build with him during the last Enzyme meeting. He pointed this jl file to me during the meeting.

**Comment by giordano** [comment]
@vchuravy was this fixed by  #12247?

**Comment by vchuravy** [comment]
Indeed.

**Comment by superustc** [comment]
@vchuravy @giordano @wsmoses  I can still reproduce this issue in the windows when CMAKE_FLAGS+=(-DENZYME_CLANG=ON) at line 97 in /home/mixu/software/Yggdrasil/E/Enzyme/build_tarballs.jl. Is it better to keep this open? Thanks!

```

julia build_tarballs.jl --debug
[ Info: Building for x86_64-w64-mingw32-cxx11-llvm_version+20
[ Info: Cached file found in /home/mixu/.julia/packages/BinaryBuilderBase/DhTtP/deps/downloads/0f03869f72df8705b832910517b47dd5b79eb4e160512602f593ed243b28715f-MacOSX10.14.sdk.tar.xz
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:394
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:473
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced 4 more times

ld.lld: error: undefined symbol: clang::SemaBase::Diag(clang::SourceLocation, unsigned int, bool)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:246
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::diagAppertainsToDecl(clang::Sema&, clang::ParsedAttr const&, clang::Decl const*) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:0
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:380
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::diagAppertainsToDecl(clang::Sema&, clang::ParsedAttr const&, clang::Decl const*) const)
>>> referenced 10 more times

ld.lld: error: undefined symbol: clang::SemaBase::SemaDiagnosticBuilder::~SemaDiagnosticBuilder()
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:246
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::diagAppertainsToDecl(clang::Sema&, clang::ParsedAttr const&, clang::Decl const*) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:0
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:380
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::diagAppertainsToDecl(clang::Sema&, clang::ParsedAttr const&, clang::Decl const*) const)
>>> referenced 10 more times

ld.lld: error: undefined symbol: clang::Expr::IgnoreParenCasts()
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:263
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)

ld.lld: error: undefined symbol: clang::AnnotateAttr::Create(clang::ASTContext&, llvm::StringRef, clang::Expr**, unsigned int, clang::SourceRange, clang::AnnotateAttr::Spelling)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:272
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:394
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)

ld.lld: error: undefined symbol: clang::DiagnosticIDs::getCustomDiagID(clang::DiagnosticIDs::CustomDiagDesc)
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/Basic/DiagnosticIDs.h:294
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/Basic/DiagnosticIDs.h:294
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeFunctionLikeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/Basic/DiagnosticIDs.h:294
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeShouldRecomputeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced 6 more times

ld.lld: error: undefined symbol: clang::SemaBase::SemaDiagnosticBuilder::getDeviceDeferredDiags() const
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/Sema/SemaBase.h:159
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:(clang::SemaBase::SemaDiagnosticBuilder const& clang::operator<<<char [10]>(clang::SemaBase::SemaDiagnosticBuilder const&, char const (&) [10]))
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/Sema/SemaBase.h:159
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:(clang::SemaBase::SemaDiagnosticBuilder const& clang::operator<<<clang::ParsedAttr>(clang::SemaBase::SemaDiagnosticBuilder const&, clang::ParsedAttr const&))
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/Sema/SemaBase.h:159
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:(clang::SemaBase::SemaDiagnosticBuilder const& clang::operator<<<char [22]>(clang::SemaBase::SemaDiagnosticBuilder const&, char const (&) [22]))

ld.lld: error: undefined symbol: clang::DeclContext::getRedeclContext()
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/AST/DeclBase.h:2276
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:(clang::VarDecl::hasLocalStorage() const)
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/AST/DeclBase.h:2276
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:(clang::VarDecl::hasLocalStorage() const)

ld.lld: error: undefined symbol: clang::Decl::castFromDeclContext(clang::DeclContext const*)
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/AST/DeclBase.h:2803
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/AST/DeclBase.h:2803
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/AST/DeclBase.h:2803
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced 3 more times

ld.lld: error: undefined symbol: clang::RecordDecl::Create(clang::ASTContext const&, clang::TagTypeKind, clang::DeclContext*, clang::SourceLocation, clang::SourceLocation, clang::IdentifierInfo*, clang::RecordDecl*)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:458
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:563
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:663
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeSparseAccumulateAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)

ld.lld: error: undefined symbol: clang::CXXRecordDecl::Create(clang::ASTContext const&, clang::TagTypeKind, clang::DeclContext*, clang::SourceLocation, clang::SourceLocation, clang::IdentifierInfo*, clang::CXXRecordDecl*, bool)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:455
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:560
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:660
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeSparseAccumulateAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)

ld.lld: error: undefined symbol: clang::TagDecl::startDefinition()
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:462
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:567
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/srcdir/Enzyme/enzyme/Enzyme/Clang/EnzymeClang.cpp:667
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeSparseAccumulateAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)

ld.lld: error: undefined symbol: clang::DeclarationName::getAsString[abi:cxx11]() const
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/AST/Decl.h:296
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeInactiveAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/AST/Decl.h:296
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeNoFreeAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)
>>> referenced by /workspace/x86_64-w64-mingw32-libgfortran5-cxx11-llvm_version+20/destdir/include/clang/AST/Decl.h:296
>>>               Enzyme/CMakeFiles/ClangEnzyme-20.dir/Clang/EnzymeClang.cpp.obj:((anonymous namespace)::EnzymeSparseAccumulateAttrInfo::handleDeclAttribute(clang::Sema&, clang::Decl*, clang::ParsedAttr const&) const)

ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: subcommand failed
Previous command exited with 1
┌ Warning: Build failed, the following log files were generated:
│   - ${WORKSPACE}/srcdir/Enzyme/build/CMakeFiles/CMakeError.log
│   - ${WORKSPACE}/srcdir/Enzyme/build/CMakeFiles/CMakeOutput.log
│   - ${WORKSPACE}/srcdir/Enzyme/build-native/BCLoad/gsl/CMakeFiles/CMakeError.log
│   - ${WORKSPACE}/srcdir/Enzyme/build-native/BCLoad/gsl/CMakeFiles/CMakeOutput.log
│   - ${WORKSPACE}/srcdir/Enzyme/build-native/CMakeFiles/CMakeError.log
│   - ${WORKSPACE}/srcdir/Enzyme/build-native/CMakeFiles/CMakeOutput.log
│ 
│ Launching debug shell:
└ @ BinaryBuilder ~/.julia/packages/BinaryBuilder/ALifR/src/AutoBuild.jl:913```

**Comment by vchuravy** [comment]
`-DENZYME_CLANG=On` builds the enzyme clang plugin. That's not the goal of the recipe here in Yggdrasil.

I am pretty sure LLVM plugins do not work on Windows in any case.
